[mysqld]
basedir = "C:/Users/Fery/Documents/Project/webserver/bin/mariadb"
datadir = "C:/Users/Fery/Documents/Project/webserver/data/mysql"
port = 3307
bind-address = 127.0.0.1
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
default-storage-engine = InnoDB
innodb_buffer_pool_size = 128M
log-error = "C:/Users/Fery/Documents/Project/webserver/logs/mariadb_error.log"
max_allowed_packet = 64M

[client]
host = 127.0.0.1
port = 3307
user = root
protocol = tcp
ssl = 0
default-character-set = utf8mb4

[mysql]
host = 127.0.0.1
port = 3307
user = root
protocol = tcp
ssl = 0
default-character-set = utf8mb4

[mariadb-client]
host = 127.0.0.1
port = 3307
user = root
protocol = tcp
ssl = 0
default-character-set = utf8mb4
